# Generated by Django 4.0.4 on 2023-03-20 17:28

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import my_blog.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=64)),
                ('middleName', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('lastName', models.CharField(default='', max_length=64)),
                ('info', ckeditor.fields.RichTextField(blank=True, default="... haven't decided yet ...", null=True)),
                ('image', models.ImageField(upload_to=my_blog.models.authorImg_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='EntertainmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise', models.CharField(default='', max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=64)),
                ('lastName', models.CharField(default='', max_length=64)),
                ('nickName', models.CharField(default='', max_length=64, unique=True)),
                ('socialMedia', models.CharField(default='', max_length=300, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=my_blog.models.image_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='LiteratureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScienceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('content', ckeditor.fields.RichTextField(blank=True, default='... to be continued ...', null=True)),
                ('readyToLounch', models.BooleanField(default=False)),
                ('tags', models.CharField(default='', max_length=200, unique=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=my_blog.models.file_directory_path)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.author')),
                ('expertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.expertise')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('content', ckeditor.fields.RichTextField(blank=True, default='... to be continued ...', null=True)),
                ('readyToLounch', models.BooleanField(default=False)),
                ('tags', models.CharField(default='', max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=my_blog.models.file_directory_path)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.author')),
                ('expertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.expertise')),
                ('featuring', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_blog.guest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('content', ckeditor.fields.RichTextField(blank=True, default='... to be continued ...', null=True)),
                ('readyToLounch', models.BooleanField(default=False)),
                ('tags', models.CharField(default='', max_length=200, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.author')),
                ('expertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.expertise')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.volume')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=150, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('file', models.FileField(upload_to=my_blog.models.file_directory_path)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.artcategory')),
                ('expertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.expertise')),
            ],
        ),
        migrations.CreateModel(
            name='Entertainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('content', ckeditor.fields.RichTextField(blank=True, default='... to be continued ...', null=True)),
                ('readyToLounch', models.BooleanField(default=False)),
                ('tags', models.CharField(default='', max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=my_blog.models.file_directory_path)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.entertainmentcategory')),
                ('expertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.expertise')),
                ('featuring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.guest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('content', ckeditor.fields.RichTextField(blank=True, default='... to be continued ...', null=True)),
                ('readyToLounch', models.BooleanField(default=False)),
                ('tags', models.CharField(default='', max_length=200, unique=True)),
                ('number', models.SmallIntegerField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.volume')),
                ('expertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.expertise')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('content', ckeditor.fields.RichTextField(blank=True, default='... to be continued ...', null=True)),
                ('readyToLounch', models.BooleanField(default=False)),
                ('tags', models.CharField(default='', max_length=200, unique=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=my_blog.models.file_directory_path)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.author')),
                ('expertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.expertise')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.literaturecategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='author',
            name='expertise',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='my_blog.expertise'),
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('content', ckeditor.fields.RichTextField(blank=True, default='... to be continued ...', null=True)),
                ('readyToLounch', models.BooleanField(default=False)),
                ('tags', models.CharField(default='', max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=my_blog.models.image_directory_path)),
                ('matherials', models.CharField(max_length=100)),
                ('dimentionX', models.PositiveSmallIntegerField(blank=True)),
                ('dimentionY', models.PositiveSmallIntegerField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.artcategory')),
                ('expertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.expertise')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
