# Generated by Django 4.0.4 on 2023-04-03 16:54

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryArt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryEntertainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryLiterature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryScience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=64)),
                ('lastName', models.CharField(default='', max_length=64)),
                ('nickName', models.CharField(default='', max_length=64)),
                ('socialMedia', models.CharField(default='', max_length=300)),
                ('image', models.ImageField(null=True, upload_to='media/authors')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=64)),
                ('middleName', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('lastName', models.CharField(default='', max_length=64)),
                ('info', ckeditor.fields.RichTextField(blank=True, default="... haven't decided yet ...", null=True)),
                ('image', models.ImageField(null=True, upload_to='media/authors')),
                ('readyToLounch', models.BooleanField(default=False)),
                ('expertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.expertise')),
            ],
        ),
    ]
