# Generated by Django 4.2 on 2023-05-18 14:22

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("my_blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "quote",
                    ckeditor.fields.RichTextField(
                        blank=True, default="... to be continued ...", null=True
                    ),
                ),
                ("readyToLaunch", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="my_blog.author"
                    ),
                ),
            ],
        ),
    ]
