# Generated by Django 4.0.4 on 2023-03-20 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='expertise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.expertise'),
        ),
    ]
