# Generated by Django 4.2 on 2023-05-18 14:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("my_blog", "0002_quotes"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Quotes",
            new_name="Quote",
        ),
    ]
