# Generated by Django 4.0.4 on 2023-04-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0002_remove_author_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/authors'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/authors'),
        ),
    ]
