# Generated by Django 4.2 on 2023-05-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_blog", "0004_alter_quote_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="quote",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
