# Generated by Django 4.2 on 2023-05-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_blog", "0005_alter_quote_quote"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="frame",
            field=models.ImageField(blank=True, null=True, upload_to="authors"),
        ),
    ]
