# Generated by Django 4.2 on 2023-05-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_blog", "0006_author_frame"),
    ]

    operations = [
        migrations.AddField(
            model_name="poem",
            name="number",
            field=models.SmallIntegerField(null=True),
        ),
    ]
