# Generated by Django 4.2 on 2023-04-06 22:06

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0006_remove_guest_info_guest_readytolounch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('content', ckeditor.fields.RichTextField(blank=True, default='... to be continued ...', null=True)),
                ('readyToLaunch', models.BooleanField(default=False)),
                ('cover', models.ImageField(upload_to='covers')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.author')),
                ('expertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.expertise')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.categoryliterature')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='guest',
            name='lastName',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='socialMedia',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.RenameModel(
            old_name='CategoryEntertainment',
            new_name='CategoryPost',
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('content', ckeditor.fields.RichTextField(blank=True, default='... to be continued ...', null=True)),
                ('readyToLaunch', models.BooleanField(default=False)),
                ('cover', models.ImageField(upload_to='covers')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.author')),
                ('expertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.expertise')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('content', ckeditor.fields.RichTextField(blank=True, default='... to be continued ...', null=True)),
                ('readyToLaunch', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='posts')),
                ('tags', models.CharField(default='', max_length=200, unique=True)),
                ('promote', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.categorypost')),
                ('expertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.expertise')),
                ('featuring', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_blog.guest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('content', ckeditor.fields.RichTextField(blank=True, default='... to be continued ...', null=True)),
                ('readyToLaunch', models.BooleanField(default=False)),
                ('promote', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.author')),
                ('expertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.expertise')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.volume')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=64, unique=True)),
                ('file', models.FileField(upload_to='patterns')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.categoryart')),
                ('expertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.expertise')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('content', ckeditor.fields.RichTextField(blank=True, default='... to be continued ...', null=True)),
                ('readyToLaunch', models.BooleanField(default=False)),
                ('number', models.SmallIntegerField(null=True)),
                ('promote', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.book')),
                ('expertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.expertise')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('content', ckeditor.fields.RichTextField(blank=True, default='... to be continued ...', null=True)),
                ('readyToLaunch', models.BooleanField(default=False)),
                ('materials', models.CharField(max_length=100)),
                ('dimentionX', models.SmallIntegerField(null=True)),
                ('dimentionY', models.SmallIntegerField(null=True)),
                ('image', models.ImageField(upload_to='artworks')),
                ('promote', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.categoryart')),
                ('expertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.expertise')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
