# Generated by Django 4.2 on 2023-05-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_blog", "0007_poem_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.ImageField(null=True, upload_to="covers"),
        ),
        migrations.AlterField(
            model_name="volume",
            name="cover",
            field=models.ImageField(null=True, upload_to="covers"),
        ),
    ]
