# Generated by Django 4.2 on 2023-05-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_blog", "0008_alter_book_cover_alter_volume_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="covers"),
        ),
        migrations.AlterField(
            model_name="volume",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="covers"),
        ),
    ]
