# Generated by Django 4.2 on 2023-06-03 13:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("my_blog", "0009_alter_book_cover_alter_volume_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="acknowledgment",
            field=ckeditor.fields.RichTextField(
                blank=True, default="... to be continued ...", null=True
            ),
        ),
        migrations.AddField(
            model_name="volume",
            name="acknowledgment",
            field=ckeditor.fields.RichTextField(
                blank=True, default="... to be continued ...", null=True
            ),
        ),
    ]
