# Generated by Django 4.2 on 2023-06-14 14:42

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("my_blog", "0010_book_acknowledgment_volume_acknowledgment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Science",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, unique=True)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "content",
                    ckeditor.fields.RichTextField(
                        blank=True, default="... to be continued ...", null=True
                    ),
                ),
                ("readyToLaunch", models.BooleanField(default=False)),
                (
                    "tags",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                ("image", models.ImageField(upload_to="posts")),
                ("promote", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="my_blog.author"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_blog.categorypost",
                    ),
                ),
                (
                    "expertise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_blog.expertise",
                    ),
                ),
                (
                    "featuring",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_blog.guest",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
