# Generated by Django 4.2 on 2023-06-14 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("my_blog", "0011_science"),
    ]

    operations = [
        migrations.AlterField(
            model_name="science",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="my_blog.categoryscience",
            ),
        ),
        migrations.AlterField(
            model_name="science",
            name="image",
            field=models.ImageField(upload_to="science"),
        ),
    ]
