# Generated by Django 4.2 on 2023-08-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_blog", "0014_science"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoryart",
            name="category_en",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="categoryliterature",
            name="category_en",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="categorypost",
            name="category_en",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="categoryscience",
            name="category_en",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="expertise",
            name="expertise_en",
            field=models.CharField(default="", max_length=64),
        ),
    ]
