# Generated by Django 4.2 on 2023-04-03 20:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0003_alter_author_image_alter_guest_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='info',
            field=ckeditor.fields.RichTextField(blank=True, default="... haven't decided yet ...", null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='info',
            field=ckeditor.fields.RichTextField(blank=True, default="... haven't decided yet ...", null=True),
        ),
    ]
