# Generated by Django 4.2 on 2023-04-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0004_author_info_guest_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='authors'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='authors'),
        ),
    ]
