# Generated by Django 4.2 on 2023-04-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0005_alter_author_image_alter_guest_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='info',
        ),
        migrations.AddField(
            model_name='guest',
            name='readyToLounch',
            field=models.BooleanField(default=False),
        ),
    ]
