# Generated by Django 4.2 on 2023-04-07 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0008_artwork_tags_book_tags_chapter_tags_poem_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_blog.categorypost'),
        ),
        migrations.AlterField(
            model_name='post',
            name='featuring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_blog.guest'),
        ),
    ]
