# Generated by Django 4.2 on 2023-05-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_blog", "0011_alter_guest_lastname_alter_guest_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guest",
            name="lastName",
            field=models.CharField(blank=True, default="", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="guest",
            name="nickName",
            field=models.CharField(default="", max_length=64),
        ),
    ]
